# Generated by Django 6.0.5 on 2026-07-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='package_type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Luxury', 'Luxury'), ('Wildlife', 'Wildlife'), ('Cultural', 'Cultural'), ('Trekking', 'Trekking')], default='Adventure', max_length=20),
        ),
    ]
