# Generated by Django 6.0.5 on 2026-07-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_tourpackage_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='rating',
        ),
    ]
